# <b><u><i>mxmh_case2_preprocessing </u>----</b></i>

In [1]:
# FOR PATH RECOGNISION ----

from pathlib import Path

print("Current Folder:")
print(Path.cwd())

print("\nParent:")
print(Path.cwd().parent)

Current Folder:
c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\mxmh_survey_results

Parent:
c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks

In [2]:
# IGNORE WARNING --

import warnings

warnings.filterwarnings("ignore")

In [3]:
# IMPORTING ALL THE NECESSARY LIBRARIES --

# Data Handling

import pandas as pd
import numpy as np

# Visualization

import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing

from sklearn.preprocessing import (
    LabelEncoder,
    StandardScaler,
    MinMaxScaler
)

# Train Test Split

from sklearn.model_selection import (
    train_test_split,
    GridSearchCV,
    cross_val_score
)

# Models

from sklearn.ensemble import (
    RandomForestClassifier,
    RandomForestRegressor
)

from xgboost import (
    XGBClassifier,
    XGBRegressor
)

# Evaluation

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# Model Saving

import joblib

# Display

pd.set_option(
    "display.max_columns",
    None
)

sns.set_style("whitegrid")

print("all the necessary libraries are imported sucessfully:")
print("🎉🎉🎉🎉")

all the necessary libraries are imported sucessfully:
🎉🎉🎉🎉

In [4]:
# DISPLAY SETTINGS --

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)
sns.set_style("whitegrid")

In [6]:
# LOADING DATASET --

# current folder = Calmify_AI/notebooks/mental_health_status
CURRENT_DIR = Path.cwd()

# Calmify_AI root folder
BASE_DIR = CURRENT_DIR.parents[1]

# dataset path = Calmify_AI/notebooks/preprocesssed/mxmh_feature_engineered.csv
DATASET_PATH = BASE_DIR / "datasets" / "mxmh_survey_results.csv"

print("Current Dir :", CURRENT_DIR)
print("Base Dir    :", BASE_DIR)
print("Dataset Path:", DATASET_PATH)

df = pd.read_csv(DATASET_PATH)

print("Dataset loaded successfully:✅✅✅✅")
print("Shape:", df.shape)
df.head()

Current Dir : c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\mxmh_survey_results
Base Dir    : c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI
Dataset Path: c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\datasets\mxmh_survey_results.csv
Dataset loaded successfully:✅✅✅✅
Shape: (736, 33)

,Timestamp,Age,Primary streaming service,Hours per day,While working,Instrumentalist,Composer,Fav genre,Exploratory,Foreign languages,BPM,Frequency [Classical],Frequency [Country],Frequency [EDM],Frequency [Folk],Frequency [Gospel],Frequency [Hip hop],Frequency [Jazz],Frequency [K pop],Frequency [Latin],Frequency [Lofi],Frequency [Metal],Frequency [Pop],Frequency [R&B],Frequency [Rap],Frequency [Rock],Frequency [Video game music],Anxiety,Depression,Insomnia,OCD,Music effects,Permissions
0,8/27/2022 19:29:02,18.0,Spotify,3.0,Yes,Yes,Yes,Latin,Yes,Yes,156.0,Rarely,Never,Rarely,Never,Never,Sometimes,Never,Very frequently,Very frequently,Rarely,Never,Very frequently,Sometimes,Very frequently,Never,Sometimes,3.0,0.0,1.0,0.0,NaN,I understand.
1,8/27/2022 19:57:31,63.0,Pandora,1.5,Yes,No,No,Rock,Yes,No,119.0,Sometimes,Never,Never,Rarely,Sometimes,Rarely,Very frequently,Rarely,Sometimes,Rarely,Never,Sometimes,Sometimes,Rarely,Very frequently,Rarely,7.0,2.0,2.0,1.0,NaN,I understand.
2,8/27/2022 21:28:18,18.0,Spotify,4.0,No,No,No,Video game music,No,Yes,132.0,Never,Never,Very frequently,Never,Never,Rarely,Rarely,Very frequently,Never,Sometimes,Sometimes,Rarely,Never,Rarely,Rarely,Very frequently,7.0,7.0,10.0,2.0,No effect,I understand.
3,8/27/2022 21:40:40,61.0,YouTube Music,2.5,Yes,No,Yes,Jazz,Yes,Yes,84.0,Sometimes,Never,Never,Rarely,Sometimes,Never,Very frequently,Sometimes,Very frequently,Sometimes,Never,Sometimes,Sometimes,Never,Never,Never,9.0,7.0,3.0,3.0,Improve,I understand.
4,8/27/2022 21:54:47,18.0,Spotify,4.0,Yes,No,No,R&B,Yes,No,107.0,Never,Never,Rarely,Never,Rarely,Very frequently,Never,Very frequently,Sometimes,Sometimes,Never,Sometimes,Very frequently,Very frequently,Never,Rarely,7.0,2.0,5.0,9.0,Improve,I understand.

In [7]:
# columns --

df.columns.tolist()

['Timestamp',
 'Age',
 'Primary streaming service',
 'Hours per day',
 'While working',
 'Instrumentalist',
 'Composer',
 'Fav genre',
 'Exploratory',
 'Foreign languages',
 'BPM',
 'Frequency [Classical]',
 'Frequency [Country]',
 'Frequency [EDM]',
 'Frequency [Folk]',
 'Frequency [Gospel]',
 'Frequency [Hip hop]',
 'Frequency [Jazz]',
 'Frequency [K pop]',
 'Frequency [Latin]',
 'Frequency [Lofi]',
 'Frequency [Metal]',
 'Frequency [Pop]',
 'Frequency [R&B]',
 'Frequency [Rap]',
 'Frequency [Rock]',
 'Frequency [Video game music]',
 'Anxiety',
 'Depression',
 'Insomnia',
 'OCD',
 'Music effects',
 'Permissions']

In [9]:

# CLEAN COLUMN NAMES --

df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
      .str.replace("[", "", regex=False)
      .str.replace("]", "", regex=False)
)

print(df.columns.tolist())
df.head()

['timestamp', 'age', 'primary_streaming_service', 'hours_per_day', 'while_working', 'instrumentalist', 'composer', 'fav_genre', 'exploratory', 'foreign_languages', 'bpm', 'frequency_classical', 'frequency_country', 'frequency_edm', 'frequency_folk', 'frequency_gospel', 'frequency_hip_hop', 'frequency_jazz', 'frequency_k_pop', 'frequency_latin', 'frequency_lofi', 'frequency_metal', 'frequency_pop', 'frequency_r&b', 'frequency_rap', 'frequency_rock', 'frequency_video_game_music', 'anxiety', 'depression', 'insomnia', 'ocd', 'music_effects', 'permissions']

,timestamp,age,primary_streaming_service,hours_per_day,while_working,instrumentalist,composer,fav_genre,exploratory,foreign_languages,bpm,frequency_classical,frequency_country,frequency_edm,frequency_folk,frequency_gospel,frequency_hip_hop,frequency_jazz,frequency_k_pop,frequency_latin,frequency_lofi,frequency_metal,frequency_pop,frequency_r&b,frequency_rap,frequency_rock,frequency_video_game_music,anxiety,depression,insomnia,ocd,music_effects,permissions
0,8/27/2022 19:29:02,18.0,Spotify,3.0,Yes,Yes,Yes,Latin,Yes,Yes,156.0,Rarely,Never,Rarely,Never,Never,Sometimes,Never,Very frequently,Very frequently,Rarely,Never,Very frequently,Sometimes,Very frequently,Never,Sometimes,3.0,0.0,1.0,0.0,NaN,I understand.
1,8/27/2022 19:57:31,63.0,Pandora,1.5,Yes,No,No,Rock,Yes,No,119.0,Sometimes,Never,Never,Rarely,Sometimes,Rarely,Very frequently,Rarely,Sometimes,Rarely,Never,Sometimes,Sometimes,Rarely,Very frequently,Rarely,7.0,2.0,2.0,1.0,NaN,I understand.
2,8/27/2022 21:28:18,18.0,Spotify,4.0,No,No,No,Video game music,No,Yes,132.0,Never,Never,Very frequently,Never,Never,Rarely,Rarely,Very frequently,Never,Sometimes,Sometimes,Rarely,Never,Rarely,Rarely,Very frequently,7.0,7.0,10.0,2.0,No effect,I understand.
3,8/27/2022 21:40:40,61.0,YouTube Music,2.5,Yes,No,Yes,Jazz,Yes,Yes,84.0,Sometimes,Never,Never,Rarely,Sometimes,Never,Very frequently,Sometimes,Very frequently,Sometimes,Never,Sometimes,Sometimes,Never,Never,Never,9.0,7.0,3.0,3.0,Improve,I understand.
4,8/27/2022 21:54:47,18.0,Spotify,4.0,Yes,No,No,R&B,Yes,No,107.0,Never,Never,Rarely,Never,Rarely,Very frequently,Never,Very frequently,Sometimes,Sometimes,Never,Sometimes,Very frequently,Very frequently,Never,Rarely,7.0,2.0,5.0,9.0,Improve,I understand.

In [10]:
rename_map = {
    "primary_streaming_service": "streaming_service",
    "hours_per_day": "hours_per_day",
    "while_working": "while_working",
    "foreign_languages": "foreign_languages",
    "fav_genre": "fav_genre",
    "music_effects": "music_effects",

    "frequency_classical": "freq_classical",
    "frequency_country": "freq_country",
    "frequency_edm": "freq_edm",
    "frequency_folk": "freq_folk",
    "frequency_gospel": "freq_gospel",
    "frequency_hip_hop": "freq_hip_hop",
    "frequency_jazz": "freq_jazz",
    "frequency_k_pop": "freq_k_pop",
    "frequency_latin": "freq_latin",
    "frequency_lofi": "freq_lofi",
    "frequency_metal": "freq_metal",
    "frequency_pop": "freq_pop",
    "frequency_r&b": "freq_rnb",
    "frequency_rap": "freq_rap",
    "frequency_rock": "freq_rock",
    "frequency_video_game_music": "freq_video_game_music"
}

df.rename(columns=rename_map, inplace=True)

print(df.columns.tolist())

['timestamp', 'age', 'streaming_service', 'hours_per_day', 'while_working', 'instrumentalist', 'composer', 'fav_genre', 'exploratory', 'foreign_languages', 'bpm', 'freq_classical', 'freq_country', 'freq_edm', 'freq_folk', 'freq_gospel', 'freq_hip_hop', 'freq_jazz', 'freq_k_pop', 'freq_latin', 'freq_lofi', 'freq_metal', 'freq_pop', 'freq_rnb', 'freq_rap', 'freq_rock', 'freq_video_game_music', 'anxiety', 'depression', 'insomnia', 'ocd', 'music_effects', 'permissions']

In [11]:

# TARGET CLEANING --

# We only keep valid music effect classes for classification

df["music_effects"] = df["music_effects"].astype(str).str.strip().str.lower()

valid_classes = ["improve", "no effect", "worsen"]

df = df[df["music_effects"].isin(valid_classes)].copy()

print("Shape after target cleaning:", df.shape)
print(df["music_effects"].value_counts(dropna=False))

Shape after target cleaning: (728, 33)
music_effects
improve      542
no effect    169
worsen        17
Name: count, dtype: int64

In [12]:
# -----------------------------
# DROP COLUMNS NOT NEEDED
# -----------------------------

drop_cols = ["permissions"]

# timestamp ko later features ke liye use nahi karna hai case 2 me
# so directly drop kar sakte hain
if "timestamp" in df.columns:
    drop_cols.append("timestamp")

existing_drop_cols = [col for col in drop_cols if col in df.columns]
df.drop(columns=existing_drop_cols, inplace=True)

print("Dropped columns:", existing_drop_cols)
print("Current shape:", df.shape)

Dropped columns: ['permissions', 'timestamp']
Current shape: (728, 31)

In [13]:

# MISSING VALUES --

missing = df.isnull().sum().sort_values(ascending=False)
missing = missing[missing > 0]

print("Missing values:\n")
print(missing)

Missing values:

bpm                  104
foreign_languages      3
instrumentalist        3
while_working          2
age                    1
streaming_service      1
dtype: int64

In [14]:

# HANDLE MISSING VALUES --

# numeric columns
numeric_cols = df.select_dtypes(include=["int64", "float64"]).columns.tolist()

# categorical columns
categorical_cols = df.select_dtypes(include=["object"]).columns.tolist()

# fill numeric with median
for col in numeric_cols:
    df[col] = df[col].fillna(df[col].median())

# fill categorical with mode
for col in categorical_cols:
    df[col] = df[col].fillna(df[col].mode()[0])

print("Missing values after filling:")
print(df.isnull().sum().sum())

Missing values after filling:
0

In [16]:
# -----------------------------
# CLEAN TEXT VALUES
# -----------------------------

for col in categorical_cols:
    df[col] = df[col].astype(str).str.strip().str.lower()

# <b><u><i>FEATURE ENGINEERED </U>----</B></I>

In [17]:
# -----------------------------
# MAP MUSIC FREQUENCY COLUMNS
# -----------------------------

frequency_map = {
    "never": 0,
    "rarely": 1,
    "sometimes": 2,
    "very frequently": 3
}

freq_cols = [
    "freq_classical", "freq_country", "freq_edm", "freq_folk",
    "freq_gospel", "freq_hip_hop", "freq_jazz", "freq_k_pop",
    "freq_latin", "freq_lofi", "freq_metal", "freq_pop",
    "freq_rnb", "freq_rap", "freq_rock", "freq_video_game_music"
]

for col in freq_cols:
    df[col] = df[col].map(frequency_map)

print(df[freq_cols].head())

   freq_classical  freq_country  freq_edm  freq_folk  freq_gospel  \
2               0             0         3          0            0
3               2             0         0          1            2
4               0             0         1          0            1
5               1             2         0          0            0
6               2             0         1          2            1

   freq_hip_hop  freq_jazz  freq_k_pop  freq_latin  freq_lofi  freq_metal  \
2             1          1           3           0          2           2
3             0          3           2           3          2           0
4             3          0           3           2          2           0
5             2          3           3           1          3           1
6             1          2           0           1          1           1

   freq_pop  freq_rnb  freq_rap  freq_rock  freq_video_game_music
2         1         0         1          1                      3
3         2         2         0          0                      0
4         2         3         3          0                      1
5         3         3         3          3                      0
6         1         1         0          0                      2

In [18]:

# MAP YES/NO COLUMNS --

yes_no_map = {
    "yes": 1,
    "no": 0
}

binary_cols = [
    "while_working",
    "instrumentalist",
    "composer",
    "exploratory",
    "foreign_languages"
]

for col in binary_cols:
    df[col] = df[col].map(yes_no_map)

print(df[binary_cols].head())

   while_working  instrumentalist  composer  exploratory  foreign_languages
2              0                0         0            0                  1
3              1                0         1            1                  1
4              1                0         0            1                  0
5              1                1         1            1                  1
6              1                1         0            1                  1

In [19]:

# COMPOSITE MENTAL SYMPTOM FEATURE --

df["mental_symptom_score"] = (
    df["anxiety"] +
    df["depression"] +
    df["insomnia"] +
    df["ocd"]
)

df["mental_symptom_avg"] = df["mental_symptom_score"] / 4

df[["anxiety", "depression", "insomnia", "ocd",
    "mental_symptom_score", "mental_symptom_avg"]].head()

,anxiety,depression,insomnia,ocd,mental_symptom_score,mental_symptom_avg
2,7.0,7.0,10.0,2.0,26.0,6.50
3,9.0,7.0,3.0,3.0,22.0,5.50
4,7.0,2.0,5.0,9.0,23.0,5.75
5,8.0,8.0,7.0,7.0,30.0,7.50
6,4.0,8.0,6.0,0.0,18.0,4.50

In [20]:
# -----------------------------
# MUSIC ENGAGEMENT SCORE
# -----------------------------

df["music_engagement_score"] = (
    df["hours_per_day"] +
    df["while_working"] +
    df["instrumentalist"] +
    df["composer"] +
    df["exploratory"]
)

df[["hours_per_day", "while_working", "instrumentalist",
    "composer", "exploratory", "music_engagement_score"]].head()

,hours_per_day,while_working,instrumentalist,composer,exploratory,music_engagement_score
2,4.0,0,0,0,0,4.0
3,2.5,1,0,1,1,5.5
4,4.0,1,0,0,1,6.0
5,5.0,1,1,1,1,9.0
6,3.0,1,1,0,1,6.0

In [21]:

# GENRE DIVERSITY SCORE --

# kitne genres user at least sometimes sunta hai

df["genre_diversity_score"] = (df[freq_cols] >= 2).sum(axis=1)

df[["genre_diversity_score"]].head()

   genre_diversity_score
2                      5
3                      8
4                      7
5                      9
6                      4

In [22]:

# CALM MUSIC SCORE --

# sleep / anxiety support ke liye useful genres ka aggregate

calm_cols = ["freq_classical", "freq_lofi", "freq_jazz", "freq_folk"]

df["calm_music_score"] = df[calm_cols].mean(axis=1)

df[["calm_music_score"]].head()

   calm_music_score
2              0.75
3              2.00
4              0.50
5              1.75
6              1.75

In [23]:

# HIGH ENERGY MUSIC SCORE --

energy_cols = ["freq_edm", "freq_hip_hop", "freq_rap", "freq_metal", "freq_rock"]

df["high_energy_score"] = df[energy_cols].mean(axis=1)

df[["high_energy_score"]].head()

   high_energy_score
2                1.6
3                0.0
4                1.4
5                1.8
6                0.6

In [25]:

mainstream_cols = ["freq_pop", "freq_rnb", "freq_latin", "freq_country"]

df["mainstream_music_score"] = df[mainstream_cols].mean(axis=1)

df[["mainstream_music_score"]].head()

   mainstream_music_score
2                    0.25
3                    1.75
4                    1.75
5                    2.25
6                    0.75

In [26]:

# BPM CLEANING --


df["bpm"] = df["bpm"].clip(lower=40, upper=250)

df["bpm"].describe()

count    728.000000
mean     122.881868
std       31.236900
min       40.000000
25%      105.000000
50%      120.000000
75%      140.000000
max      250.000000
Name: bpm, dtype: float64

In [27]:

# BPM BAND --

df["bpm_band"] = pd.cut(
    df["bpm"],
    bins=[0, 90, 120, 160, 300],
    labels=["low_bpm", "medium_bpm", "high_bpm", "very_high_bpm"]
)

df["bpm_band"].value_counts(dropna=False)

bpm_band
medium_bpm       329
high_bpm         211
low_bpm          103
very_high_bpm     85
Name: count, dtype: int64

In [28]:

# LISTENING BAND --

df["listening_band"] = pd.cut(
    df["hours_per_day"],
    bins=[-1, 2, 5, 24],
    labels=["low_listener", "moderate_listener", "heavy_listener"]
)

df["listening_band"].value_counts(dropna=False)

listening_band
low_listener         332
moderate_listener    262
heavy_listener       134
Name: count, dtype: int64

In [29]:

# MENTAL HEALTH BAND --

df["mental_health_band"] = pd.cut(
    df["mental_symptom_score"],
    bins=[-1, 10, 20, 40],
    labels=["low", "moderate", "high"]
)

df["mental_health_band"].value_counts(dropna=False)

mental_health_band
moderate    295
high        264
low         169
Name: count, dtype: int64

In [30]:

# TARGET ENCODING --

target_map = {
    "improve": 0,
    "no effect": 1,
    "worsen": 2
}

df["music_effects_label"] = df["music_effects"].map(target_map)

print(df[["music_effects", "music_effects_label"]].head())
print(df["music_effects_label"].value_counts())

  music_effects  music_effects_label
2     no effect                    1
3       improve                    0
4       improve                    0
5       improve                    0
6       improve                    0
music_effects_label
0    542
1    169
2     17
Name: count, dtype: int64

In [31]:


raw_symptom_cols = ["anxiety", "depression", "insomnia", "ocd"]

df.drop(columns=raw_symptom_cols, inplace=True)

print("Dropped raw symptom columns:", raw_symptom_cols)
print("Current shape:", df.shape)

Dropped raw symptom columns: ['anxiety', 'depression', 'insomnia', 'ocd']
Current shape: (728, 38)

In [32]:


categorical_cols_after_fe = df.select_dtypes(include=["object", "category"]).columns.tolist()

print("Categorical columns before encoding:")
print(categorical_cols_after_fe)

Categorical columns before encoding:
['streaming_service', 'fav_genre', 'music_effects', 'bpm_band', 'listening_band', 'mental_health_band']

In [33]:
df = pd.get_dummies(
    df,
    columns=categorical_cols_after_fe,
    drop_first=False
)

print("Shape after encoding:", df.shape)
df.head()

Shape after encoding: (728, 67)

,age,hours_per_day,while_working,instrumentalist,composer,exploratory,foreign_languages,bpm,freq_classical,freq_country,freq_edm,freq_folk,freq_gospel,freq_hip_hop,freq_jazz,freq_k_pop,freq_latin,freq_lofi,freq_metal,freq_pop,freq_rnb,freq_rap,freq_rock,freq_video_game_music,mental_symptom_score,mental_symptom_avg,music_engagement_score,genre_diversity_score,calm_music_score,high_energy_score,mainstream_music_score,music_effects_label,streaming_service_apple music,streaming_service_i do not use a streaming service.,streaming_service_other streaming service,streaming_service_pandora,streaming_service_spotify,streaming_service_youtube music,fav_genre_classical,fav_genre_country,fav_genre_edm,fav_genre_folk,fav_genre_gospel,fav_genre_hip hop,fav_genre_jazz,fav_genre_k pop,fav_genre_latin,fav_genre_lofi,fav_genre_metal,fav_genre_pop,fav_genre_r&b,fav_genre_rap,fav_genre_rock,fav_genre_video game music,music_effects_improve,music_effects_no effect,music_effects_worsen,bpm_band_low_bpm,bpm_band_medium_bpm,bpm_band_high_bpm,bpm_band_very_high_bpm,listening_band_low_listener,listening_band_moderate_listener,listening_band_heavy_listener,mental_health_band_low,mental_health_band_moderate,mental_health_band_high
2,18.0,4.0,0,0,0,0,1,132.0,0,0,3,0,0,1,1,3,0,2,2,1,0,1,1,3,26.0,6.50,4.0,5,0.75,1.6,0.25,1,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,True,False,False,False,True,False,False,True,False,False,False,True
3,61.0,2.5,1,0,1,1,1,84.0,2,0,0,1,2,0,3,2,3,2,0,2,2,0,0,0,22.0,5.50,5.5,8,2.00,0.0,1.75,0,False,False,False,False,False,True,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,False,False,False,True
4,18.0,4.0,1,0,0,1,0,107.0,0,0,1,0,1,3,0,3,2,2,0,2,3,3,0,1,23.0,5.75,6.0,7,0.50,1.4,1.75,0,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False,False,True,False,False,False,True,False,False,False,True,False,False,False,True
5,18.0,5.0,1,1,1,1,1,86.0,1,2,0,0,0,2,3,3,1,3,1,3,3,3,3,0,30.0,7.50,9.0,9,1.75,1.8,2.25,0,False,False,False,False,True,False,False,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,True,False,False,True,False,False,False,False,True,False,False,False,True
6,18.0,3.0,1,1,0,1,1,66.0,2,0,1,2,1,1,2,0,1,1,1,1,1,0,0,2,18.0,4.50,6.0,4,1.75,0.6,0.75,0,False,False,False,False,False,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,True,True,False,False,True,False,False,False,False,True,False,False,True,False

In [34]:

# REMOVE DUPLICATE COLUMNS --

df = df.loc[:, ~df.columns.duplicated()].copy()

print("Shape after removing duplicate columns:", df.shape)

Shape after removing duplicate columns: (728, 67)

In [37]:

# PATH SETUP --

CURRENT_DIR = Path.cwd()                         
BASE_DIR = CURRENT_DIR.parents[1]              
DATASET_PATH = BASE_DIR / "datasets" / "mxmh_survey_results.csv"

PREPROCESSED_DIR = CURRENT_DIR.parent / "preprocessed"
PREPROCESSED_DIR.mkdir(parents=True, exist_ok=True)

In [38]:

# SAVE FINAL MODEL READY DATASET --

save_path = PREPROCESSED_DIR / "mxmh_case2_model_ready.csv"

df.to_csv(save_path, index=False)

print("MXMH Case 2 preprocessed dataset saved successfully")
print("Saved at:", save_path)

MXMH Case 2 preprocessed dataset saved successfully
Saved at: c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\preprocessed\mxmh_case2_model_ready.csv