# <B><I><U>stress_dataset_preprocessing </U>----</B></I>

In [1]:
# FOR PATH RECOGNISION ----

from pathlib import Path

print("Current Folder:")
print(Path.cwd())

print("\nParent:")
print(Path.cwd().parent)

Current Folder:
c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\Stress_Dataset

Parent:
c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks

In [2]:
# IGNORE WARNING --

import warnings

warnings.filterwarnings("ignore")

In [3]:
# IMPORTING ALL THE NECESSARY LIBRARIES --

# Data Handling

import pandas as pd
import numpy as np

# Visualization

import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing

from sklearn.preprocessing import (
    LabelEncoder,
    StandardScaler,
    MinMaxScaler
)

# Train Test Split

from sklearn.model_selection import (
    train_test_split,
    GridSearchCV,
    cross_val_score
)

# Models

from sklearn.ensemble import (
    RandomForestClassifier,
    RandomForestRegressor
)

from xgboost import (
    XGBClassifier,
    XGBRegressor
)

# Evaluation

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# Model Saving

import joblib

# Display

pd.set_option(
    "display.max_columns",
    None
)

sns.set_style("whitegrid")

print("all the necessary libraries are imported sucessfully:")
print("🎉🎉🎉🎉")

all the necessary libraries are imported sucessfully:
🎉🎉🎉🎉

In [4]:
# DISPLAY SETTINGS --

pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 200)
sns.set_style("whitegrid")

In [8]:
# LOADING DATASET --

# current folder = Calmify_AI/notebooks/mental_health_status
CURRENT_DIR = Path.cwd()

# Calmify_AI root folder
BASE_DIR = CURRENT_DIR.parents[1]

# dataset path = Calmify_AI/datasets/mental_health_dataset.csv
DATASET_PATH = BASE_DIR / "datasets" / "Stress_Dataset.csv"

print("Current Dir :", CURRENT_DIR)
print("Base Dir    :", BASE_DIR)
print("Dataset Path:", DATASET_PATH)

df = pd.read_csv(DATASET_PATH)

print("Dataset loaded successfully:✅✅✅✅")
print("Shape:", df.shape)
df.head()

Current Dir : c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\Stress_Dataset
Base Dir    : c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI
Dataset Path: c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\datasets\Stress_Dataset.csv
Dataset loaded successfully:✅✅✅✅
Shape: (843, 26)

,Gender,Age,Have you recently experienced stress in your life?,Have you noticed a rapid heartbeat or palpitations?,Have you been dealing with anxiety or tension recently?,Do you face any sleep problems or difficulties falling asleep?,Have you been dealing with anxiety or tension recently?.1,Have you been getting headaches more often than usual?,Do you get irritated easily?,Do you have trouble concentrating on your academic tasks?,Have you been feeling sadness or low mood?,Have you been experiencing any illness or health issues?,Do you often feel lonely or isolated?,Do you feel overwhelmed with your academic workload?,"Are you in competition with your peers, and does it affect you?",Do you find that your relationship often causes you stress?,Are you facing any difficulties with your professors or instructors?,Is your working environment unpleasant or stressful?,Do you struggle to find time for relaxation and leisure activities?,Is your hostel or home environment causing you difficulties?,Do you lack confidence in your academic performance?,Do you lack confidence in your choice of academic subjects?,Academic and extracurricular activities conflicting for you?,Do you attend classes regularly?,Have you gained/lost weight?,Which type of stress do you primarily experience?
0,0,20,3,4,2,5,1,2,1,2,2,3,1,5,1,2,3,1,4,1,2,1,3,1,2,Eustress (Positive Stress) - Stress that motiv...
1,0,20,2,3,2,1,1,1,1,4,2,1,2,1,2,4,3,2,1,1,3,2,1,4,2,Eustress (Positive Stress) - Stress that motiv...
2,0,20,5,4,2,2,1,3,4,2,3,2,3,4,5,2,2,2,2,1,4,1,1,2,1,Eustress (Positive Stress) - Stress that motiv...
3,1,20,3,4,3,2,2,3,4,3,5,2,4,1,2,3,1,1,2,1,2,1,1,5,3,Eustress (Positive Stress) - Stress that motiv...
4,0,20,3,3,3,2,2,4,4,4,4,1,1,1,2,1,2,3,1,2,2,4,2,2,2,Eustress (Positive Stress) - Stress that motiv...

In [9]:
# INFORMATION --

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 843 entries, 0 to 842
Data columns (total 26 columns):
 #   Column                                                                Non-Null Count  Dtype
---  ------                                                                --------------  -----
 0   Gender                                                                843 non-null    int64
 1   Age                                                                   843 non-null    int64
 2   Have you recently experienced stress in your life?                    843 non-null    int64
 3   Have you noticed a rapid heartbeat or palpitations?                   843 non-null    int64
 4   Have you been dealing with anxiety or tension recently?               843 non-null    int64
 5   Do you face any sleep problems or difficulties falling asleep?        843 non-null    int64
 6   Have you been dealing with anxiety or tension recently?.1             843 non-null    int64
 7   Have you been getting headaches more often than usual?                843 non-null    int64
 8   Do you get irritated easily?                                          843 non-null    int64
 9   Do you have trouble concentrating on your academic tasks?             843 non-null    int64
 10  Have you been feeling sadness or low mood?                            843 non-null    int64
 11  Have you been experiencing any illness or health issues?              843 non-null    int64
 12  Do you often feel lonely or isolated?                                 843 non-null    int64
 13  Do you feel overwhelmed with your academic workload?                  843 non-null    int64
 14  Are you in competition with your peers, and does it affect you?       843 non-null    int64
 15  Do you find that your relationship often causes you stress?           843 non-null    int64
 16  Are you facing any difficulties with your professors or instructors?  843 non-null    int64
 17  Is your working environment unpleasant or stressful?                  843 non-null    int64
 18  Do you struggle to find time for relaxation and leisure activities?   843 non-null    int64
 19  Is your hostel or home environment causing you difficulties?          843 non-null    int64
 20  Do you lack confidence in your academic performance?                  843 non-null    int64
 21  Do you lack confidence in your choice of academic subjects?           843 non-null    int64
 22  Academic and extracurricular activities conflicting for you?          843 non-null    int64
 23  Do you attend classes regularly?                                      843 non-null    int64
 24  Have you gained/lost weight?                                          843 non-null    int64
 25  Which type of stress do you primarily experience?                     843 non-null    object
dtypes: int64(25), object(1)
memory usage: 171.4+ KB

In [10]:
# columns list --

df.columns.tolist()

['Gender',
 'Age',
 'Have you recently experienced stress in your life?',
 'Have you noticed a rapid heartbeat or palpitations?',
 'Have you been dealing with anxiety or tension recently?',
 'Do you face any sleep problems or difficulties falling asleep?',
 'Have you been dealing with anxiety or tension recently?.1',
 'Have you been getting headaches more often than usual?',
 'Do you get irritated easily?',
 'Do you have trouble concentrating on your academic tasks?',
 'Have you been feeling sadness or low mood?',
 'Have you been experiencing any illness or health issues?',
 'Do you often feel lonely or isolated?',
 'Do you feel overwhelmed with your academic workload?',
 'Are you in competition with your peers, and does it affect you?',
 'Do you find that your relationship often causes you stress?',
 'Are you facing any difficulties with your professors or instructors?',
 'Is your working environment unpleasant or stressful?',
 'Do you struggle to find time for relaxation and leisure activities?',
 'Is your hostel or home environment causing you difficulties?',
 'Do you lack confidence in your academic performance?',
 'Do you lack confidence in your choice of academic subjects?',
 'Academic and extracurricular activities conflicting for you?',
 'Do you attend classes regularly?',
 'Have you gained/lost weight?',
 'Which type of stress do you primarily experience?']

In [11]:

# BASIC INSPECTION --

print("Shape:", df.shape)
print("\nColumns:\n", df.columns.tolist())

print("\nInfo:\n")
print(df.info())

print("\nMissing values:\n")
print(df.isnull().sum())

print("\nDuplicate rows:", df.duplicated().sum())

Shape: (843, 26)

Columns:
 ['Gender', 'Age', 'Have you recently experienced stress in your life?', 'Have you noticed a rapid heartbeat or palpitations?', 'Have you been dealing with anxiety or tension recently?', 'Do you face any sleep problems or difficulties falling asleep?', 'Have you been dealing with anxiety or tension recently?.1', 'Have you been getting headaches more often than usual?', 'Do you get irritated easily?', 'Do you have trouble concentrating on your academic tasks?', 'Have you been feeling sadness or low mood?', 'Have you been experiencing any illness or health issues?', 'Do you often feel lonely or isolated?', 'Do you feel overwhelmed with your academic workload?', 'Are you in competition with your peers, and does it affect you?', 'Do you find that your relationship often causes you stress?', 'Are you facing any difficulties with your professors or instructors?', 'Is your working environment unpleasant or stressful?', 'Do you struggle to find time for relaxation and leisure activities?', 'Is your hostel or home environment causing you difficulties?', 'Do you lack confidence in your academic performance?', 'Do you lack confidence in your choice of academic subjects?', 'Academic and extracurricular activities conflicting for you?', 'Do you attend classes regularly?', 'Have you gained/lost weight?', 'Which type of stress do you primarily experience?']

Info:

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 843 entries, 0 to 842
Data columns (total 26 columns):
 #   Column                                                                Non-Null Count  Dtype
---  ------                                                                --------------  -----
 0   Gender                                                                843 non-null    int64
 1   Age                                                                   843 non-null    int64
 2   Have you recently experienced stress in your life?                    843 non-null    int64
 3   Have you noticed a rapid heartbeat or palpitations?                   843 non-null    int64
 4   Have you been dealing with anxiety or tension recently?               843 non-null    int64
 5   Do you face any sleep problems or difficulties falling asleep?        843 non-null    int64
 6   Have you been dealing with anxiety or tension recently?.1             843 non-null    int64
 7   Have you been getting headaches more often than usual?                843 non-null    int64
 8   Do you get irritated easily?                                          843 non-null    int64
 9   Do you have trouble concentrating on your academic tasks?             843 non-null    int64
 10  Have you been feeling sadness or low mood?                            843 non-null    int64
 11  Have you been experiencing any illness or health issues?              843 non-null    int64
 12  Do you often feel lonely or isolated?                                 843 non-null    int64
 13  Do you feel overwhelmed with your academic workload?                  843 non-null    int64
 14  Are you in competition with your peers, and does it affect you?       843 non-null    int64
 15  Do you find that your relationship often causes you stress?           843 non-null    int64
 16  Are you facing any difficulties with your professors or instructors?  843 non-null    int64
 17  Is your working environment unpleasant or stressful?                  843 non-null    int64
 18  Do you struggle to find time for relaxation and leisure activities?   843 non-null    int64
 19  Is your hostel or home environment causing you difficulties?          843 non-null    int64
 20  Do you lack confidence in your academic performance?                  843 non-null    int64
 21  Do you lack confidence in your choice of academic subjects?           843 non-null    int64
 22  Academic and extracurricular activities conflicting for you?          843 non-null    int64
 23  Do you attend classes regularly?                                      843 non-null    int64
 24  Have you gained/lost weight?                                          843 non-null    int64
 25  Which type of stress do you primarily experience?                     843 non-null    object
dtypes: int64(25), object(1)
memory usage: 171.4+ KB
None

Missing values:

Gender                                                                  0
Age                                                                     0
Have you recently experienced stress in your life?                      0
Have you noticed a rapid heartbeat or palpitations?                     0
Have you been dealing with anxiety or tension recently?                 0
Do you face any sleep problems or difficulties falling asleep?          0
Have you been dealing with anxiety or tension recently?.1               0
Have you been getting headaches more often than usual?                  0
Do you get irritated easily?                                            0
Do you have trouble concentrating on your academic tasks?               0
Have you been feeling sadness or low mood?                              0
Have you been experiencing any illness or health issues?                0
Do you often feel lonely or isolated?                                   0
Do you feel overwhelmed with your academic workload?                    0
Are you in competition with your peers, and does it affect you?         0
Do you find that your relationship often causes you stress?             0
Are you facing any difficulties with your professors or instructors?    0
Is your working environment unpleasant or stressful?                    0
Do you struggle to find time for relaxation and leisure activities?     0
Is your hostel or home environment causing you difficulties?            0
Do you lack confidence in your academic performance?                    0
Do you lack confidence in your choice of academic subjects?             0
Academic and extracurricular activities conflicting for you?            0
Do you attend classes regularly?                                        0
Have you gained/lost weight?                                            0
Which type of stress do you primarily experience?                       0
dtype: int64

Duplicate rows: 27

In [28]:
# =========================
# CLEAN TARGET LABELS
# =========================

df["stress_type"] = df["stress_type"].astype(str).str.strip()

def clean_stress_type(x):
    x_lower = x.lower().strip()

    if "eustress" in x_lower:
        return "eustress"
    elif "distress" in x_lower:
        return "distress"
    elif "no stress" in x_lower:
        return "no_stress"
    else:
        return x_lower

df["stress_type"] = df["stress_type"].apply(clean_stress_type)

print(df["stress_type"].value_counts(dropna=False))

stress_type
eustress     768
no_stress     43
distress      32
Name: count, dtype: int64

In [12]:

# RENAME COLUMNS --

rename_map = {
    "Gender": "gender",
    "Age": "age",
    "Have you recently experienced stress in your life?": "recent_stress",
    "Have you noticed a rapid heartbeat or palpitations?": "rapid_heartbeat",
    "Have you been dealing with anxiety or tension recently?": "anxiety_tension",
    "Do you face any sleep problems or difficulties falling asleep?": "sleep_problems",
    "Have you been dealing with anxiety or tension recently?.1": "anxiety_tension_dup",
    "Have you been getting headaches more often than usual?": "headaches",
    "Do you get irritated easily?": "irritability",
    "Do you have trouble concentrating on your academic tasks?": "concentration_issues",
    "Have you been feeling sadness or low mood?": "low_mood",
    "Have you been experiencing any illness or health issues?": "health_issues",
    "Do you often feel lonely or isolated?": "loneliness",
    "Do you feel overwhelmed with your academic workload?": "academic_overload",
    "Are you in competition with your peers, and does it affect you?": "peer_competition_stress",
    "Do you find that your relationship often causes you stress?": "relationship_stress",
    "Are you facing any difficulties with your professors or instructors?": "professor_issues",
    "Is your working environment unpleasant or stressful?": "work_environment_stress",
    "Do you struggle to find time for relaxation and leisure activities?": "lack_of_relaxation",
    "Is your hostel or home environment causing you difficulties?": "home_environment_stress",
    "Do you lack confidence in your academic performance?": "low_academic_confidence",
    "Do you lack confidence in your choice of academic subjects?": "subject_confidence_issues",
    "Academic and extracurricular activities conflicting for you?": "academic_extracurricular_conflict",
    "Do you attend classes regularly?": "class_attendance",
    "Have you gained/lost weight?": "weight_change",
    "Which type of stress do you primarily experience?": "stress_type"
}

df = df.rename(columns=rename_map)

print("Renamed columns:\n")
print(df.columns.tolist())

Renamed columns:

['gender', 'age', 'recent_stress', 'rapid_heartbeat', 'anxiety_tension', 'sleep_problems', 'anxiety_tension_dup', 'headaches', 'irritability', 'concentration_issues', 'low_mood', 'health_issues', 'loneliness', 'academic_overload', 'peer_competition_stress', 'relationship_stress', 'professor_issues', 'work_environment_stress', 'lack_of_relaxation', 'home_environment_stress', 'low_academic_confidence', 'subject_confidence_issues', 'academic_extracurricular_conflict', 'class_attendance', 'weight_change', 'stress_type']

In [13]:

# TARGET COLUMN INSPECTION --

print(df["stress_type"].value_counts(dropna=False))

stress_type
Eustress (Positive Stress) - Stress that motivates and enhances performance.       768
No Stress - Currently experiencing minimal to no stress.                            43
Distress (Negative Stress) - Stress that causes anxiety and impairs well-being.     32
Name: count, dtype: int64

In [14]:

# CLEAN TARGET LABELS --

df["stress_type"] = df["stress_type"].astype(str).str.strip()

def clean_stress_type(x):
    x_lower = x.lower()
    
    if "eustress" in x_lower:
        return "eustress"
    elif "distress" in x_lower:
        return "distress"
    else:
        return x_lower

df["stress_type"] = df["stress_type"].apply(clean_stress_type)

print(df["stress_type"].value_counts(dropna=False))

stress_type
eustress                                                    768
no stress - currently experiencing minimal to no stress.     43
distress                                                     32
Name: count, dtype: int64

In [15]:

# CHECK DUPLICATE ANXIETY COLUMN --


if "anxiety_tension_dup" in df.columns:
    same_values = (df["anxiety_tension"] == df["anxiety_tension_dup"]).all()
    print("Is duplicate anxiety column exactly same?", same_values)

Is duplicate anxiety column exactly same? False

In [16]:
if "anxiety_tension_dup" in df.columns:
    if (df["anxiety_tension"] == df["anxiety_tension_dup"]).all():
        df.drop(columns=["anxiety_tension_dup"], inplace=True)
        print("Dropped duplicate column: anxiety_tension_dup")
    else:
        print("Duplicate column not dropped because values differ")
        
print("Current shape:", df.shape)

Duplicate column not dropped because values differ
Current shape: (843, 26)

In [17]:

# FINAL MISSING VALUE CHECK --

missing = df.isnull().sum()
missing = missing[missing > 0]

print("Missing values > 0:\n")
print(missing if len(missing) > 0 else "No missing values found")

Missing values > 0:

No missing values found

# <b><u><i>FEATURE ENGINEERING </U>----</B></I>

In [18]:

# MENTAL SYMPTOM SCORE --


mental_cols = [
    "recent_stress",
    "anxiety_tension",
    "headaches",
    "irritability",
    "concentration_issues",
    "low_mood",
    "loneliness"
]

df["mental_symptom_score"] = df[mental_cols].mean(axis=1)

df[["mental_symptom_score"]].head()

   mental_symptom_score
0              1.857143
1              2.000000
2              3.142857
3              3.571429
4              3.285714

In [19]:

# PHYSICAL STRESS SCORE --

physical_cols = [
    "rapid_heartbeat",
    "sleep_problems",
    "health_issues",
    "weight_change"
]

df["physical_stress_score"] = df[physical_cols].mean(axis=1)

df[["physical_stress_score"]].head()

   physical_stress_score
0                   3.50
1                   1.75
2                   2.25
3                   2.75
4                   2.00

In [20]:
# ACADEMIC STRESS SCORE --


academic_cols = [
    "academic_overload",
    "peer_competition_stress",
    "professor_issues",
    "low_academic_confidence",
    "subject_confidence_issues",
    "academic_extracurricular_conflict"
]

df["academic_stress_score"] = df[academic_cols].mean(axis=1)

df[["academic_stress_score"]].head()

   academic_stress_score
0               2.500000
1               2.000000
2               2.833333
3               1.333333
4               2.166667

In [21]:

# ENVIRONMENT STRES --

environment_cols = [
    "relationship_stress",
    "work_environment_stress",
    "home_environment_stress"
]

df["environment_stress_score"] = df[environment_cols].mean(axis=1)

df[["environment_stress_score"]].head()

   environment_stress_score
0                  1.333333
1                  2.333333
2                  1.666667
3                  1.666667
4                  2.000000

In [22]:

#  LIFESTYLE STRESS SCORE --


recovery_cols = [
    "sleep_problems",
    "lack_of_relaxation"
]

df["recovery_difficulty_score"] = df[recovery_cols].mean(axis=1)

df[["recovery_difficulty_score"]].head()

   recovery_difficulty_score
0                        4.5
1                        1.0
2                        2.0
3                        2.0
4                        1.5

In [23]:

# OVERALL STRESS RISK SCORE --

overall_components = [
    "mental_symptom_score",
    "physical_stress_score",
    "academic_stress_score",
    "environment_stress_score",
    "recovery_difficulty_score"
]

df["overall_stress_risk_score"] = df[overall_components].mean(axis=1)

df[["overall_stress_risk_score"]].head()

   overall_stress_risk_score
0                   2.738095
1                   1.816667
2                   2.378571
3                   2.264286
4                   2.190476

In [24]:

# ATTENDANCE RISK --


# Assume higher attendance = better
# So risk = max_scale - attendance
max_attendance_value = df["class_attendance"].max()

df["attendance_risk"] = max_attendance_value - df["class_attendance"]

df[["class_attendance", "attendance_risk"]].head()

   class_attendance  attendance_risk
0                 1                4
1                 4                1
2                 2                3
3                 5                0
4                 2                3

In [25]:
# COPING DIFFICULTY SCORE

coping_cols = [
    "lack_of_relaxation",
    "loneliness",
    "low_academic_confidence",
    "subject_confidence_issues"
]

df["coping_difficulty_score"] = df[coping_cols].mean(axis=1)

df[["coping_difficulty_score"]].head()

   coping_difficulty_score
0                     2.00
1                     2.00
2                     2.50
3                     2.25
4                     2.00

In [29]:

# TARGET ENCODING --


target_map = {
    "no_stress": 0,
    "eustress": 1,
    "distress": 2
}

df["stress_type_label"] = df["stress_type"].map(target_map)

print("Encoded target distribution:\n")
print(df["stress_type_label"].value_counts(dropna=False))

print("\nTarget mapping used:")
print(target_map)

Encoded target distribution:

stress_type_label
1    768
0     43
2     32
Name: count, dtype: int64

Target mapping used:
{'no_stress': 0, 'eustress': 1, 'distress': 2}

In [30]:
# =========================
# CHECK UNMAPPED TARGETS
# =========================

unmapped = df[df["stress_type_label"].isnull()]["stress_type"].unique()
print("Unmapped target labels:", unmapped)

Unmapped target labels: []

In [32]:
# =========================
# FINAL MODEL-READY DATAFRAME
# =========================

drop_cols = [
    "stress_type"   # original text target हटाएँगे
]

df_model = df.drop(columns=drop_cols).copy()

print("Model-ready shape:", df_model.shape)

Model-ready shape: (843, 34)

In [33]:
# columns list --

df.columns.tolist()

['gender',
 'age',
 'recent_stress',
 'rapid_heartbeat',
 'anxiety_tension',
 'sleep_problems',
 'anxiety_tension_dup',
 'headaches',
 'irritability',
 'concentration_issues',
 'low_mood',
 'health_issues',
 'loneliness',
 'academic_overload',
 'peer_competition_stress',
 'relationship_stress',
 'professor_issues',
 'work_environment_stress',
 'lack_of_relaxation',
 'home_environment_stress',
 'low_academic_confidence',
 'subject_confidence_issues',
 'academic_extracurricular_conflict',
 'class_attendance',
 'weight_change',
 'stress_type',
 'mental_symptom_score',
 'physical_stress_score',
 'academic_stress_score',
 'environment_stress_score',
 'recovery_difficulty_score',
 'overall_stress_risk_score',
 'attendance_risk',
 'coping_difficulty_score',
 'stress_type_label']

In [35]:
# =========================
# SAVE PREPROCESSED / MODEL-READY DATASET
# =========================

from pathlib import Path

# current notebook folder = notebooks/stress_dataset
CURRENT_DIR = Path.cwd()

# notebooks folder
NOTEBOOKS_DIR = CURRENT_DIR.parent

# notebooks/preprocessed
PREPROCESSED_DIR = NOTEBOOKS_DIR / "preprocessed"
PREPROCESSED_DIR.mkdir(parents=True, exist_ok=True)

# save file
save_path = PREPROCESSED_DIR / "stress_dataset_model_ready.csv"
df_model.to_csv(save_path, index=False)

print("Preprocessed stress dataset saved successfully")
print("Saved at:", save_path)

Preprocessed stress dataset saved successfully
Saved at: c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\preprocessed\stress_dataset_model_ready.csv