# <b><u><i>stress_dataset_model_building </u>----</b></i>

In [1]:
# ignoring warning --

import warnings
warnings.filterwarnings("ignore")


# importing all necessary libraries --

from pathlib import Path
import pandas as pd
import numpy as np

# preprocessing / model selection
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# models
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier

try:
    from xgboost import XGBClassifier
    xgb_available = True
except ImportError:
    xgb_available = False
    print("XGBoost not installed. RandomForest and LogisticRegression will still run.")

# evaluation
from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# save model
import joblib

print("warnings ignored:✅✅")
print("ALL NECESSARY LIBRARIES ARE IMPORTED SUCESSFULL ;")
print("🎉🎉🎉🎉")

warnings ignored:✅✅
ALL NECESSARY LIBRARIES ARE IMPORTED SUCESSFULL ;
🎉🎉🎉🎉

In [2]:

# PATH SETUP


CURRENT_DIR = Path.cwd()                 # notebooks/stress_dataset
NOTEBOOKS_DIR = CURRENT_DIR.parent       # notebooks
PREPROCESSED_DIR = NOTEBOOKS_DIR / "preprocessed"
MODELS_DIR = NOTEBOOKS_DIR / "models"

PREPROCESSED_DIR.mkdir(parents=True, exist_ok=True)
MODELS_DIR.mkdir(parents=True, exist_ok=True)

print("Current Dir      :", CURRENT_DIR)
print("Notebooks Dir    :", NOTEBOOKS_DIR)
print("Preprocessed Dir :", PREPROCESSED_DIR)
print("Models Dir       :", MODELS_DIR)

Current Dir      : c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\Stress_Dataset
Notebooks Dir    : c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks
Preprocessed Dir : c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\preprocessed
Models Dir       : c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\models

In [3]:
# ============================================================
# LOAD MODEL-READY DATASET
# ============================================================

data_path = PREPROCESSED_DIR / "stress_dataset_model_ready.csv"

df = pd.read_csv(data_path)

print("Dataset loaded successfully")
print("Shape:", df.shape)
df.head()

Dataset loaded successfully
Shape: (843, 34)

,gender,age,recent_stress,rapid_heartbeat,anxiety_tension,sleep_problems,anxiety_tension_dup,headaches,irritability,concentration_issues,...,weight_change,mental_symptom_score,physical_stress_score,academic_stress_score,environment_stress_score,recovery_difficulty_score,overall_stress_risk_score,attendance_risk,coping_difficulty_score,stress_type_label
0,0,20,3,4,2,5,1,2,1,2,...,2,1.857143,3.50,2.500000,1.333333,4.5,2.738095,4,2.00,1
1,0,20,2,3,2,1,1,1,1,4,...,2,2.000000,1.75,2.000000,2.333333,1.0,1.816667,1,2.00,1
2,0,20,5,4,2,2,1,3,4,2,...,1,3.142857,2.25,2.833333,1.666667,2.0,2.378571,3,2.50,1
3,1,20,3,4,3,2,2,3,4,3,...,3,3.571429,2.75,1.333333,1.666667,2.0,2.264286,0,2.25,1
4,0,20,3,3,3,2,2,4,4,4,...,2,3.285714,2.00,2.166667,2.000000,1.5,2.190476,3,2.00,1

In [4]:
# COLUMNS --

print("Columns in dataset:\n")
for col in df.columns:
    print(col)

Columns in dataset:

gender
age
recent_stress
rapid_heartbeat
anxiety_tension
sleep_problems
anxiety_tension_dup
headaches
irritability
concentration_issues
low_mood
health_issues
loneliness
academic_overload
peer_competition_stress
relationship_stress
professor_issues
work_environment_stress
lack_of_relaxation
home_environment_stress
low_academic_confidence
subject_confidence_issues
academic_extracurricular_conflict
class_attendance
weight_change
mental_symptom_score
physical_stress_score
academic_stress_score
environment_stress_score
recovery_difficulty_score
overall_stress_risk_score
attendance_risk
coping_difficulty_score
stress_type_label

In [7]:
# TARGET --

TARGET_COL = "stress_type_label"

In [8]:
# TARGET DISTRIBUTION --

print("Target column:", TARGET_COL)
print("\nTarget value counts:\n")
print(df[TARGET_COL].value_counts(dropna=False))

Target column: stress_type_label

Target value counts:

stress_type_label
1    768
0     43
2     32
Name: count, dtype: int64

In [9]:
# FEATURE AND TARGET --

X = df.drop(columns=[TARGET_COL]).copy()
y = df[TARGET_COL].copy()

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (843, 33)
y shape: (843,)

In [10]:
# ENCODE TARGET --

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)

print("Encoded classes:")
for i, cls in enumerate(label_encoder.classes_):
    print(i, "->", cls)

Encoded classes:
0 -> 0
1 -> 1
2 -> 2

In [11]:
# TRAIN TEXT SPLIT --

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y_encoded,
    test_size=0.2,
    random_state=42,
    stratify=y_encoded
)

print("Train shape:", X_train.shape, y_train.shape)
print("Test shape :", X_test.shape, y_test.shape)

Train shape: (674, 33) (674,)
Test shape : (169, 33) (169,)

# <B><I><U>MODEL 1</U> ----</B></I>

In [12]:
# LOGISTIC REGRESSION --

log_reg = LogisticRegression(
    max_iter=2000,
    random_state=42
)

log_reg.fit(X_train, y_train)

y_pred_lr = log_reg.predict(X_test)

acc_lr = accuracy_score(y_test, y_pred_lr)
f1_lr = f1_score(y_test, y_pred_lr, average="weighted")

print("Logistic Regression Accuracy :", round(acc_lr, 4))
print("Logistic Regression Weighted F1 :", round(f1_lr, 4))

Logistic Regression Accuracy : 0.9763
Logistic Regression Weighted F1 : 0.9744

In [14]:
print("=== Logistic Regression Classification Report ===\n")
print(classification_report(y_test, y_pred_lr))

=== Logistic Regression Classification Report ===

              precision    recall  f1-score   support

           0       1.00      0.67      0.80         9
           1       0.97      1.00      0.99       154
           2       1.00      0.83      0.91         6

    accuracy                           0.98       169
   macro avg       0.99      0.83      0.90       169
weighted avg       0.98      0.98      0.97       169

# <B><I><U>MODEL 2</U> ----</B></I>

In [15]:
# RANDOM FOREST --

rf = RandomForestClassifier(
    n_estimators=300,
    max_depth=None,
    min_samples_split=2,
    min_samples_leaf=1,
    random_state=42,
    n_jobs=-1
)

rf.fit(X_train, y_train)

y_pred_rf = rf.predict(X_test)

acc_rf = accuracy_score(y_test, y_pred_rf)
f1_rf = f1_score(y_test, y_pred_rf, average="weighted")

print("Random Forest Accuracy :", round(acc_rf, 4))
print("Random Forest Weighted F1 :", round(f1_rf, 4))

Random Forest Accuracy : 0.9645
Random Forest Weighted F1 : 0.9603

In [16]:
print("=== Random Forest Classification Report ===\n")
print(classification_report(y_test, y_pred_rf))

=== Random Forest Classification Report ===

              precision    recall  f1-score   support

           0       1.00      0.56      0.71         9
           1       0.96      1.00      0.98       154
           2       1.00      0.67      0.80         6

    accuracy                           0.96       169
   macro avg       0.99      0.74      0.83       169
weighted avg       0.97      0.96      0.96       169

# <B><U><I>MODEL 3</U> ----</B></I>

In [17]:
# XG-BOOST --

if xgb_available:
    xgb_model = XGBClassifier(
        n_estimators=300,
        max_depth=6,
        learning_rate=0.08,
        subsample=0.9,
        colsample_bytree=0.9,
        objective="multi:softmax",
        num_class=len(np.unique(y_encoded)),
        random_state=42,
        eval_metric="mlogloss"
    )

    xgb_model.fit(X_train, y_train)

    y_pred_xgb = xgb_model.predict(X_test)

    acc_xgb = accuracy_score(y_test, y_pred_xgb)
    f1_xgb = f1_score(y_test, y_pred_xgb, average="weighted")

    print("XGBoost Accuracy :", round(acc_xgb, 4))
    print("XGBoost Weighted F1 :", round(f1_xgb, 4))
else:
    acc_xgb = None
    f1_xgb = None

XGBoost Accuracy : 0.9645
XGBoost Weighted F1 : 0.9621

In [19]:
if xgb_available:
    print("=== XGBoost Classification Report ===\n")
    print(classification_report(y_test, y_pred_xgb))

=== XGBoost Classification Report ===

              precision    recall  f1-score   support

           0       0.86      0.67      0.75         9
           1       0.97      0.99      0.98       154
           2       1.00      0.67      0.80         6

    accuracy                           0.96       169
   macro avg       0.94      0.78      0.84       169
weighted avg       0.96      0.96      0.96       169

In [20]:
# MODELS COMPARISON --

results = []

results.append({
    "Model": "Logistic Regression",
    "Accuracy": acc_lr,
    "Weighted_F1": f1_lr
})

results.append({
    "Model": "Random Forest",
    "Accuracy": acc_rf,
    "Weighted_F1": f1_rf
})

if xgb_available:
    results.append({
        "Model": "XGBoost",
        "Accuracy": acc_xgb,
        "Weighted_F1": f1_xgb
    })

results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by=["Accuracy", "Weighted_F1"], ascending=False).reset_index(drop=True)

results_df

                 Model  Accuracy  Weighted_F1
0  Logistic Regression  0.976331     0.974439
1              XGBoost  0.964497     0.962062
2        Random Forest  0.964497     0.960272

In [21]:
best_model_name = results_df.loc[0, "Model"]
print("Best model is:", best_model_name)

Best model is: Logistic Regression

In [22]:
if best_model_name == "Logistic Regression":
    best_model = log_reg
elif best_model_name == "Random Forest":
    best_model = rf
elif best_model_name == "XGBoost":
    best_model = xgb_model
else:
    raise ValueError("Unexpected best model name")
    
print("Selected best model:", best_model_name)

Selected best model: Logistic Regression

In [23]:
# ============================================================
# SAVE BEST MODEL
# ============================================================

model_path = MODELS_DIR / "stress_dataset_best_model.pkl"
encoder_path = MODELS_DIR / "stress_dataset_label_encoder.pkl"
features_path = MODELS_DIR / "stress_dataset_feature_columns.pkl"

joblib.dump(best_model, model_path)
joblib.dump(label_encoder, encoder_path)
joblib.dump(list(X.columns), features_path)

print("Best model saved successfully")
print("Model path   :", model_path)
print("Encoder path :", encoder_path)
print("Features path:", features_path)

Best model saved successfully
Model path   : c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\models\stress_dataset_best_model.pkl
Encoder path : c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\models\stress_dataset_label_encoder.pkl
Features path: c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\models\stress_dataset_feature_columns.pkl

In [24]:
loaded_model = joblib.load(model_path)
loaded_encoder = joblib.load(encoder_path)
loaded_features = joblib.load(features_path)

print("Loaded model successfully")
print("Loaded encoder classes:", list(loaded_encoder.classes_))
print("Number of features:", len(loaded_features))

Loaded model successfully
Loaded encoder classes: [np.int64(0), np.int64(1), np.int64(2)]
Number of features: 33

In [25]:
sample_preds = loaded_model.predict(X_test.iloc[:5])
sample_labels = loaded_encoder.inverse_transform(sample_preds)

print("Sample predictions:")
for i, label in enumerate(sample_labels, 1):
    print(f"Sample {i}: {label}")

Sample predictions:
Sample 1: 1
Sample 2: 1
Sample 3: 2
Sample 4: 1
Sample 5: 1