# <b><i><u>student_stress_sleep_screen </u>----</b></i>

In [1]:
# FOR PATH RECOGNISION ----

from pathlib import Path

print("Current Folder:")
print(Path.cwd())

print("\nParent:")
print(Path.cwd().parent)

Current Folder:
c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\student_stress_sleep_screen

Parent:
c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks

In [2]:
# IGNORE WARNING --

import warnings

warnings.filterwarnings("ignore")

In [3]:
# IMPORTING ALL THE NECESSARY LIBRARIES --

# Data Handling

import pandas as pd
import numpy as np

# Visualization

import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing

from sklearn.preprocessing import (
    LabelEncoder,
    StandardScaler,
    MinMaxScaler
)

# Train Test Split

from sklearn.model_selection import (
    train_test_split,
    GridSearchCV,
    cross_val_score
)

# Models

from sklearn.ensemble import (
    RandomForestClassifier,
    RandomForestRegressor
)

from xgboost import (
    XGBClassifier,
    XGBRegressor
)

# Evaluation

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix,
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# Model Saving

import joblib

# Display

pd.set_option(
    "display.max_columns",
    None
)

sns.set_style("whitegrid")

print("all the necessary libraries are imported sucessfully:")
print("🎉🎉🎉🎉")

all the necessary libraries are imported sucessfully:
🎉🎉🎉🎉

In [9]:
BASE_DIR = Path.cwd().parents[1]

DATASET_PATH = BASE_DIR / "datasets" / "student_stress_sleep_screen.csv"
PREPROCESSED_DIR = BASE_DIR / "preprocessed"

PREPROCESSED_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print("BASE_DIR:", BASE_DIR)
print("DATASET_PATH:", DATASET_PATH)
print("PREPROCESSED_DIR:", PREPROCESSED_DIR)

BASE_DIR: c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI
DATASET_PATH: c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\datasets\student_stress_sleep_screen.csv
PREPROCESSED_DIR: c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\preprocessed

In [10]:
# loading dataset --

BASE_DIR = Path.cwd().parents[1]

df = pd.read_csv(
    BASE_DIR / "datasets" / "student_stress_sleep_screen.csv"
)

df.head()

,student_id,age,gender,sleep_hours,screen_time_hours,stress_level,study_hours,physical_activity,caffeine_intake,academic_pressure
0,S001,22,Female,5.9,2.7,Medium,7.4,Yes,3,High
1,S002,25,Male,5.9,7.6,High,4.6,No,2,Low
2,S003,23,Male,8.0,3.2,Low,2.0,Yes,3,High
3,S004,22,Female,7.8,11.4,Medium,4.4,Yes,3,High
4,S005,20,Other,6.0,2.9,Medium,6.7,No,0,High

In [6]:
# SHAPE OF DATASET --
 
print(df.shape)

(500, 10)

In [7]:
# INFORMATION OF DATASET --

print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   student_id         500 non-null    object
 1   age                500 non-null    int64
 2   gender             500 non-null    object
 3   sleep_hours        500 non-null    float64
 4   screen_time_hours  500 non-null    float64
 5   stress_level       500 non-null    object
 6   study_hours        500 non-null    float64
 7   physical_activity  500 non-null    object
 8   caffeine_intake    500 non-null    int64
 9   academic_pressure  500 non-null    object
dtypes: float64(3), int64(2), object(5)
memory usage: 39.2+ KB
None

In [8]:
# DESCRIPTION OF DATASET --

print(df.describe(include="all"))

       student_id         age gender  sleep_hours  screen_time_hours  \
count         500  500.000000    500   500.000000         500.000000
unique        500         NaN      3          NaN                NaN
top          S500         NaN   Male          NaN                NaN
freq            1         NaN    171          NaN                NaN
mean          NaN   21.532000    NaN     6.547200           7.109600
std           NaN    2.244784    NaN     1.436098           2.906366
min           NaN   18.000000    NaN     4.000000           2.000000
25%           NaN   20.000000    NaN     5.300000           4.575000
50%           NaN   22.000000    NaN     6.500000           7.300000
75%           NaN   23.000000    NaN     7.800000           9.500000
max           NaN   25.000000    NaN     9.000000          12.000000

       stress_level  study_hours physical_activity  caffeine_intake  \
count           500   500.000000               500        500.00000
unique            3          NaN                 2              NaN
top          Medium          NaN                No              NaN
freq            338          NaN               266              NaN
mean            NaN     5.019000               NaN          1.98000
std             NaN     1.759856               NaN          1.39409
min             NaN     2.000000               NaN          0.00000
25%             NaN     3.500000               NaN          1.00000
50%             NaN     5.000000               NaN          2.00000
75%             NaN     6.600000               NaN          3.00000
max             NaN     8.000000               NaN          4.00000

       academic_pressure
count                500
unique                 3
top                  Low
freq                 173
mean                 NaN
std                  NaN
min                  NaN
25%                  NaN
50%                  NaN
75%                  NaN
max                  NaN

In [11]:
# checking null values --

missing = df.isnull().sum()

print("Missing values per column:")
print(missing)

Missing values per column:
student_id           0
age                  0
gender               0
sleep_hours          0
screen_time_hours    0
stress_level         0
study_hours          0
physical_activity    0
caffeine_intake      0
academic_pressure    0
dtype: int64

In [12]:
# WORKING COPY --

wellness_df = df.copy()

print("Working copy created.")
wellness_df.head()

Working copy created.

,student_id,age,gender,sleep_hours,screen_time_hours,stress_level,study_hours,physical_activity,caffeine_intake,academic_pressure
0,S001,22,Female,5.9,2.7,Medium,7.4,Yes,3,High
1,S002,25,Male,5.9,7.6,High,4.6,No,2,Low
2,S003,23,Male,8.0,3.2,Low,2.0,Yes,3,High
3,S004,22,Female,7.8,11.4,Medium,4.4,Yes,3,High
4,S005,20,Other,6.0,2.9,Medium,6.7,No,0,High

In [17]:
# DROPPING UNNECESSARY COLUMNS --

# wellness_df.drop(
#     columns=["student_id"],
#     inplace=True
# )

# print("student_id dropped.")

# <B><I><U>STANDARDISING CATEGIRICAL DATA </U>----</B></I>

In [18]:
# Check unique values of categorical columns --

categorical_cols = [
    "gender",
    "stress_level",
    "physical_activity",
    "academic_pressure"
]

for col in categorical_cols:
    print(f"\n{col}:")
    print(wellness_df[col].value_counts(dropna=False))

gender:
gender
Male      171
Other     168
Female    161
Name: count, dtype: int64

stress_level:
stress_level
Medium    338
High      102
Low        60
Name: count, dtype: int64

physical_activity:
physical_activity
No     266
Yes    234
Name: count, dtype: int64

academic_pressure:
academic_pressure
Low       173
Medium    166
High      161
Name: count, dtype: int64

In [20]:
# STANDARDISE TEXT VALUES --

for col in categorical_cols:
    wellness_df[col] = (
        wellness_df[col]
        .astype(str)
        .str.strip()
        .str.lower()
    )

print("Categorical text standardized.")

Categorical text standardized.

In [21]:
for col in categorical_cols:
    print(f"\n{col}:")
    print(wellness_df[col].value_counts(dropna=False))

gender:
gender
male      171
other     168
female    161
Name: count, dtype: int64

stress_level:
stress_level
medium    338
high      102
low        60
Name: count, dtype: int64

physical_activity:
physical_activity
no     266
yes    234
Name: count, dtype: int64

academic_pressure:
academic_pressure
low       173
medium    166
high      161
Name: count, dtype: int64

# <B><I><U>ENCODING </U>----</B></I>

In [22]:
# GENDER --

gender_map = {
    "female": 0,
    "male": 1,
    "other": 2
}

wellness_df["gender"] = wellness_df["gender"].map(gender_map)

print("Gender encoded.")

Gender encoded.

In [23]:
# STRESS LEVEL --

stress_map = {
    "low": 0,
    "medium": 1,
    "high": 2
}

wellness_df["stress_level"] = wellness_df["stress_level"].map(stress_map)

print("Stress level encoded.")

Stress level encoded.

In [24]:
# PHYSICAL ACTIVITY --

activity_map = {
    "no": 0,
    "yes": 1
}

wellness_df["physical_activity"] = (
    wellness_df["physical_activity"]
    .map(activity_map)
)

print("Physical activity encoded.")

Physical activity encoded.

In [25]:
# ACADEMIC PRESURE --

pressure_map = {
    "low": 0,
    "medium": 1,
    "high": 2
}

wellness_df["academic_pressure"] = (
    wellness_df["academic_pressure"]
    .map(pressure_map)
)

print("Academic pressure encoded.")

Academic pressure encoded.

In [28]:
# 
wellness_df.isnull().sum()

age                  0
gender               0
sleep_hours          0
screen_time_hours    0
stress_level         0
study_hours          0
physical_activity    0
caffeine_intake      0
academic_pressure    0
dtype: int64

# <B><I><U>FEATURE ENGINNERING </U>---</B></I>

In [29]:
# derived features --

# 1. Sleep quality proxy
# ideal sleep near 7.5–8 hours
wellness_df["sleep_balance_score"] = (
    10 - abs(wellness_df["sleep_hours"] - 7.5) * 2
)

wellness_df["sleep_balance_score"] = (
    wellness_df["sleep_balance_score"]
    .clip(lower=0, upper=10)
)

# 2. Digital overload score
wellness_df["digital_overload_score"] = (
    wellness_df["screen_time_hours"] / 12 * 10
).clip(0, 10)

# 3. Study load score
wellness_df["study_load_score"] = (
    wellness_df["study_hours"] / 8 * 10
).clip(0, 10)

# 4. Stress pressure score
wellness_df["stress_pressure_score"] = (
    wellness_df["stress_level"] * 3
    + wellness_df["academic_pressure"] * 2
)

# 5. Lifestyle support score
wellness_df["lifestyle_support_score"] = (
    wellness_df["physical_activity"] * 5
    + wellness_df["sleep_balance_score"] * 0.5
)

print("Derived features created.")
wellness_df.head()

Derived features created.

,age,gender,sleep_hours,screen_time_hours,stress_level,study_hours,physical_activity,caffeine_intake,academic_pressure,sleep_balance_score,digital_overload_score,study_load_score,stress_pressure_score,lifestyle_support_score
0,22,0,5.9,2.7,1,7.4,1,3,2,6.8,2.250000,9.250,7,8.4
1,25,1,5.9,7.6,2,4.6,0,2,0,6.8,6.333333,5.750,6,3.4
2,23,1,8.0,3.2,0,2.0,1,3,2,9.0,2.666667,2.500,4,9.5
3,22,0,7.8,11.4,1,4.4,1,3,2,9.4,9.500000,5.500,7,9.7
4,20,2,6.0,2.9,1,6.7,0,0,2,7.0,2.416667,8.375,7,3.5

In [30]:
# SLEEP DEFICIT --

wellness_df["sleep_deficit"] = (
    8 - wellness_df["sleep_hours"]
).clip(lower=0)

In [31]:
#CAFFEIN BURDEN -- 
 
wellness_df["caffeine_burden"] = (
    wellness_df["caffeine_intake"] / 4 * 10
).clip(0, 10)

In [33]:
# TARGET () WELLNESS SCORE --

wellness_df["wellness_score"] = (
    50
    + (wellness_df["sleep_balance_score"] * 3.0)
    + (wellness_df["physical_activity"] * 12.0)
    - (wellness_df["stress_level"] * 10.0)
    - (wellness_df["academic_pressure"] * 8.0)
    - (wellness_df["digital_overload_score"] * 1.8)
    - (wellness_df["caffeine_burden"] * 1.2)
    - (wellness_df["study_load_score"] * 1.0)
)

wellness_df["wellness_score"] = (
    wellness_df["wellness_score"]
    .clip(lower=0, upper=100)
    .round(2)
)

wellness_df[[
    "sleep_hours",
    "screen_time_hours",
    "stress_level",
    "physical_activity",
    "academic_pressure",
    "caffeine_intake",
    "wellness_score"
]].head()

,sleep_hours,screen_time_hours,stress_level,physical_activity,academic_pressure,caffeine_intake,wellness_score
0,5.9,2.7,1,1,2,3,34.10
1,5.9,7.6,2,0,0,2,27.25
2,8.0,3.2,0,1,2,3,56.70
3,7.8,11.4,1,1,2,3,32.60
4,6.0,2.9,1,0,2,0,32.28

In [39]:
# SAVING DATASET --

OUTPUT_PATH = PREPROCESSED_DIR / "wellness_feature_engineered.csv"

wellness_df.to_csv(
    OUTPUT_PATH,
    index=False
)

print("Preprocessed wellness dataset saved successfully.")
print("Saved at:", OUTPUT_PATH)

Preprocessed wellness dataset saved successfully.
Saved at: c:\Users\mohit\OneDrive\Desktop\Calmify AI\Calmify_AI\Calmify_AI\notebooks\preprocessed\wellness_feature_engineered.csv